https://github.com/hunkim/DeepLearningZeroToAll/blob/master/lab-01-basics.ipynb

In [1]:
import tensorflow as tf
tf.__version__

ModuleNotFoundError: No module named 'tensorflow'

데이터셋 선언

In [ ]:
tf.set_random_seed(777)  # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

빌드-피드 방식 사용을 위해 placeholder를 이용

In [ ]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

시드를 이용해 w1~w3, bias값을 무작위 rank 1, shape 1 데이터(벡터)로 초기화

In [ ]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

가설함수: 설계 했던 그대로

In [ ]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost function, gradient descent optimizer 구현 및 session run  
learning rate는 1e-5(1*10^-5)로 매우 작은 값으로 설정  

이전과 마찬가지로 cost, hypothesis, train값을 기록하기 위해 변수 선언, print

In [ ]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


결과값(추정치)는 y값에 수렴하게 됨. 2000에서 cost가 4.73(최소값)을 가질 때,  
예상값은 대략 155, 182, 182, 194, 142이며  
y_data = [152., 185., 180., 196., 142.]에 근접  

x와 w의 개수가 많아질수록 이 방식의 코드 구현은 한계가 있음  
따라서 Matrix를 이용해야 함  


---
output reset 후 실행할 것

In [1]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

입력데이터에서 인스턴스의 수는 확장 가능하도록 None으로,  
각 인스턴스에서 element의 개수는 3으로 고정  

출력 역시 마찬가지
(Review) [#inst(==n), #var] * [#var, #output] = [#inst(==n), #output]

In [2]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

Weight, bias의 shape는 #var, #output에 따라 고정됨  
상대적으로 코드 줄 수가 줄어듦  

In [3]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

나머지 코드, 결과값은 동일  
matrix multiplication(Matmul 이용)

In [4]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


st:  5.7920403 
Prediction:
 [[155.56291]
 [182.13885]
 [182.23573]
 [194.50717]
 [141.0766 ]]
40 Cost:  5.7710066 
Prediction:
 [[155.55511]
 [182.14413]
 [182.23325]
 [194.50604]
 [141.08298]]
50 Cost:  5.7501135 
Prediction:
 [[155.54735]
 [182.1494 ]
 [182.23079]
 [194.50493]
 [141.08934]]
60 Cost:  5.7293425 
Prediction:
 [[155.53958]
 [182.15462]
 [182.2283 ]
 [194.50377]
 [141.09566]]
70 Cost:  5.7086334 
Prediction:
 [[155.53186]
 [182.15988]
 [182.22586]
 [194.50269]
 [141.10197]]
80 Cost:  5.688061 
Prediction:
 [[155.52414]
 [182.1651 ]
 [182.22343]
 [194.50157]
 [141.10829]]
90 Cost:  5.6675863 
Prediction:
 [[155.51643]
 [182.1703 ]
 [182.22098]
 [194.50044]
 [141.11455]]
100 Cost:  5.6471696 
Prediction:
 [[155.50876]
 [182.17552]
 [182.21854]
 [194.49936]
 [141.12082]]
110 Cost:  5.6269403 
Prediction:
 [[155.50111]
 [182.18071]
 [182.21613]
 [194.49825]
 [141.12706]]
120 Cost:  5.6067524 
Prediction:
 [[155.49347]
 [182.18587]
 [182.21367]
 [194.49715]
 [141.13329]]
130