Loading data from file  
np.float32 자료형으로 불러옴  
numpy의 loadtxt 메소드 이용  
텍스트파일 전체를 읽어 ,로 데이터를 구분하고 읽어들임(csv는 ,로 구분된 벡터 데이터)  

Slicing:
xy에 csv파일 데이터테이블이 읽히고, slicing을 이용해서 x_data에는 xy의 모든 instance(row)에서 0번 열부터 마지막 열(-1) 전까지 읽고 저장  
y_data에는 모든 instance에서 마지막 열(-1)을 저장

In [12]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]


데이터 확인

In [13]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


'\n[[ 73.  80.  75.]\n [ 93.  88.  93.]\n ...\n [ 76.  83.  71.]\n [ 96.  93.  95.]] \nx_data shape: (25, 3)\n[[152.]\n [185.]\n ...\n [149.]\n [192.]] \ny_data shape: (25, 1)\n'

나머지 절차는 모두 동일

In [15]:


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

# train output
'''
0 Cost: 21027.0 
Prediction:
 [[22.048063 ]
 [21.619772 ]
 ...
 [31.36112  ]
 [24.986364 ]]
10 Cost: 95.976326 
Prediction:
 [[157.11063 ]
 [183.99283 ]
 ...
 [167.48862 ]
 [193.25117 ]]
 1990 Cost: 24.863274 
Prediction:
 [[154.4393  ]
 [185.5584  ]
 ...
 [158.27443 ]
 [192.79778 ]]
2000 Cost: 24.722485 
Prediction:
 [[154.42894 ]
 [185.5586  ]
 ...
 [158.24257 ]
 [192.79166 ]]
'''


49.81532 ]
 [112.41241 ]
 [175.70183 ]
 [165.95854 ]
 [143.72667 ]
 [143.48837 ]
 [185.93239 ]
 [152.57271 ]
 [151.08849 ]
 [189.3867  ]
 [144.45514 ]
 [180.2508  ]
 [176.5436  ]
 [157.77675 ]
 [175.81319 ]
 [175.18439 ]
 [166.93114 ]
 [149.89748 ]
 [191.27408 ]]
1480 Cost: 6.6180186 
Prediction:
 [[151.82439 ]
 [185.57346 ]
 [181.25075 ]
 [198.8855  ]
 [140.80615 ]
 [105.948746]
 [149.8168  ]
 [112.41516 ]
 [175.69724 ]
 [165.95242 ]
 [143.72667 ]
 [143.4852  ]
 [185.93394 ]
 [152.57434 ]
 [151.08891 ]
 [189.38426 ]
 [144.4553  ]
 [180.25378 ]
 [176.54623 ]
 [157.7797  ]
 [175.81416 ]
 [175.18193 ]
 [166.9328  ]
 [149.90215 ]
 [191.27283 ]]
1490 Cost: 6.6135955 
Prediction:
 [[151.8279 ]
 [185.57097]
 [181.2518 ]
 [198.88606]
 [140.80305]
 [105.94481]
 [149.81828]
 [112.41792]
 [175.69267]
 [165.94635]
 [143.72667]
 [143.48201]
 [185.9355 ]
 [152.57597]
 [151.08934]
 [189.38182]
 [144.45546]
 [180.25676]
 [176.54881]
 [157.78267]
 [175.81514]
 [175.17947]
 [166.93446]
 [149.9068 ]
 [1

'\n0 Cost: 21027.0 \nPrediction:\n [[22.048063 ]\n [21.619772 ]\n ...\n [31.36112  ]\n [24.986364 ]]\n10 Cost: 95.976326 \nPrediction:\n [[157.11063 ]\n [183.99283 ]\n ...\n [167.48862 ]\n [193.25117 ]]\n 1990 Cost: 24.863274 \nPrediction:\n [[154.4393  ]\n [185.5584  ]\n ...\n [158.27443 ]\n [192.79778 ]]\n2000 Cost: 24.722485 \nPrediction:\n [[154.42894 ]\n [185.5586  ]\n ...\n [158.24257 ]\n [192.79166 ]]\n'

X값을 주고 새 예측값 얻기

In [ ]:

# Ask my score
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[ 181.73277283]]
Other scores will be  [[ 145.86265564]
 [ 187.23129272]]
'''

---
넘어가기 전에 결과값 리셋  

# Queue Runner 활용

1) filename_queue에 tf.train.string_input_producer()로 여러 파일들 읽어들이기  
2) tf.TextLineReader() 클래스와 read()메소드를 이용하여 키와 값을 따로 읽어들일 수 있다.  
-> 텍스트파일을 읽어들일 때 일반적으로 사용할 수 있다.  
3) record_defaults 옵션값으로 data type을 결정해주고 decode_csv()메소드로 값들을 노드로 가져올 수 있다.

In [8]:
  
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

batch 데이터 생성
batch: 일괄적으로 처리되는 데이터 집단  
한 batch에서 training example을 10개로 지정(batch size)  
여기서 한 batch는 data-01-test-score.csv파일이므로, 여기서 샘플을 10개(10행) 만든다는 의미  
batch() 메소드를 이용해 트레이닝셋을 만든다.  

In [9]:
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
print(train_x_batch) #10개의 instance를 가진 파일이 만들어짐.
#자료형은 위에서 record_defaults를 이용해 정의됨. 소수점 -> float32
#이걸 랜덤으로 뽑는건지?

Tensor("batch_4:0", shape=(10, 3), dtype=float32)


기타사항 동일  
start_queue_runner()를 이용해 Queue Runner 실행. Session run Loop를 돌기 전에 실행함.  
train_x_batch, train_y_batch도 노드이므로 실행시켜야 함.  
x_batch, y_batch에 feed_dict를 이용해 줄 수도 있다.

In [10]:

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)




학습 과정

In [11]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

ost:  14.25075 
Prediction:
 [[153.51544]
 [186.74968]
 [182.86646]
 [198.27222]
 [143.84534]
 [105.21267]
 [146.67433]
 [106.17623]
 [174.1078 ]
 [159.6925 ]]
850 Cost:  14.180084 
Prediction:
 [[153.51053]
 [186.74786]
 [182.86192]
 [198.27504]
 [143.83856]
 [105.22013]
 [146.68683]
 [106.19989]
 [174.11655]
 [159.7181 ]]
860 Cost:  14.109993 
Prediction:
 [[153.50563 ]
 [186.74603 ]
 [182.85739 ]
 [198.27783 ]
 [143.8318  ]
 [105.22753 ]
 [146.69926 ]
 [106.223465]
 [174.12518 ]
 [159.74355 ]]
870 Cost:  14.040453 
Prediction:
 [[153.5008 ]
 [186.7442 ]
 [182.8529 ]
 [198.28061]
 [143.82504]
 [105.23489]
 [146.71167]
 [106.24697]
 [174.1338 ]
 [159.76889]]
880 Cost:  13.971454 
Prediction:
 [[153.49599 ]
 [186.74237 ]
 [182.84843 ]
 [198.28342 ]
 [143.81831 ]
 [105.24221 ]
 [146.72406 ]
 [106.270424]
 [174.14238 ]
 [159.7941  ]]
890 Cost:  13.902949 
Prediction:
 [[153.4912 ]
 [186.74051]
 [182.84398]
 [198.28618]
 [143.81157]
 [105.24947]
 [146.73639]
 [106.2938 ]
 [174.15088]
 [15

csv파일을 확인해보면, 0행부터 10개 가져왔다는걸 알 수 있음.  
batch 순서를 섞고자 할 시 shuffle_batch 메소드 활용 가능  
큐 처리를 위한 스레드를 선언한걸로 보이지만 정확히 어떤 절차인지는 모르겠음  

값 주고 테스트

In [16]:
# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

'''
Your score will be  [[185.33531]]
Other scores will be  [[178.36246]
 [177.03687]]
'''
pass

Your score will be  [[190.70442]]
Other scores will be  [[181.4022 ]
 [174.05043]]


'\nYour score will be  [[185.33531]]\nOther scores will be  [[178.36246]\n [177.03687]]\n'